# Generated by Django 5.2.11 on 2026-02-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_trim_unique_together_remove_trim_car_model_and_more'),
        ('leasing', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leasingoffer',
            name='trim',
        ),
        migrations.AddField(
            model_name='leasingoffer',
            name='variant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leasing_offers', to='catalog.variant'),
        ),
    ]
