# Generated by Django 5.2.11 on 2026-03-02 22:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0001_initial'),
        ('vehicles', '0011_mobiledepagecache'),
    ]

    operations = [
        migrations.CreateModel(
            name='Financing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=4, help_text='Annual interest rate as a decimal (e.g. 0.0499 for 4.99%)', max_digits=6)),
                ('tax_interest', models.DecimalField(decimal_places=4, help_text='Tax interest rate as a decimal', max_digits=6)),
                ('rate_type', models.CharField(choices=[('fixed', 'Fixed'), ('variable', 'Variable')], default='fixed', max_length=10)),
                ('lienholder_declaration_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('plates_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('import_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('additional_monthly', models.DecimalField(decimal_places=2, default=0, help_text='Fixed additional monthly cost', max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='DKK', max_length=3)),
                ('tax_value', models.DecimalField(decimal_places=2, max_digits=12)),
                ('mileage', models.PositiveIntegerField(help_text='Current mileage in km')),
                ('km_per_year', models.PositiveIntegerField()),
                ('tax_exempt', models.BooleanField(default=False)),
                ('yearly_greentax', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('residual_value', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('residual_deprecation_pct', models.DecimalField(blank=True, decimal_places=4, help_text='Residual deprecation as a percentage (e.g. 0.40 for 40%)', max_digits=6, null=True)),
                ('down_payment', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.PositiveSmallIntegerField(default=12)),
                ('leasing_type', models.CharField(choices=[('financial', 'Financial'), ('operating', 'Operating')], default='financial', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('financing', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='listings', to='leasing.financing')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to='vehicles.vehicle')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
