# Generated by Django 5.2.11 on 2026-03-03 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0002_financing_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='proportional_registration_tax',
            field=models.BooleanField(default=True),
        ),
    ]
