# Generated by Django 5.2.11 on 2026-03-03 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0003_listing_proportional_registration_tax'),
    ]

    operations = [
        migrations.RenameField(
            model_name='listing',
            old_name='tax_value',
            new_name='registration_tax',
        ),
    ]
