# Generated by Django 5.2.11 on 2026-03-04 00:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leasing', '0004_rename_tax_value_listing_registration_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='financing',
            name='commission',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
