# Generated by Django 5.2.11 on 2026-02-17 20:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Make',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('logo_url', models.URLField(blank=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CarModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=120)),
                ('generation', models.CharField(blank=True, max_length=50)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('body_type', models.CharField(blank=True, max_length=50)),
                ('make', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='models', to='catalog.make')),
            ],
            options={
                'ordering': ['make', 'name'],
                'unique_together': {('make', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=220)),
                ('engine_displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_cylinders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=30)),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_kw', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('torque_nm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('transmission', models.CharField(blank=True, max_length=50)),
                ('drive', models.CharField(blank=True, max_length=20)),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('top_speed_kmh', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_consumption_l100km', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('co2_g_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('electric_range_km', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, null=True)),
                ('curb_weight_kg', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('trunk_volume_l', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_from', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('source_url', models.URLField(blank=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trims', to='catalog.carmodel')),
            ],
            options={
                'ordering': ['car_model', 'name'],
                'unique_together': {('car_model', 'slug')},
            },
        ),
    ]
