# Generated by Django 5.2.11 on 2026-02-17 21:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trim',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='trim',
            name='car_model',
        ),
        migrations.AlterModelOptions(
            name='carmodel',
            options={'ordering': ['make', 'name'], 'verbose_name': 'Car Model', 'verbose_name_plural': 'Car Models'},
        ),
        migrations.AlterModelOptions(
            name='make',
            options={'ordering': ['name'], 'verbose_name': 'Make', 'verbose_name_plural': 'Makes'},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'name', 'generation')},
        ),
        migrations.RemoveField(
            model_name='make',
            name='slug',
        ),
        migrations.AddField(
            model_name='carmodel',
            name='data_id',
            field=models.IntegerField(db_index=True, help_text='auto-data.net submodel ID for generation rows; model ID for parent rows', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='parent',
            field=models.ForeignKey(blank=True, help_text="Parent model row (no generation). E.g. '3 Series' is parent of 'E90 (2005-2011)'.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generations', to='catalog.carmodel'),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='production_end',
            field=models.PositiveIntegerField(blank=True, help_text='Year', null=True),
        ),
        migrations.AddField(
            model_name='carmodel',
            name='production_start',
            field=models.PositiveIntegerField(blank=True, help_text='Year', null=True),
        ),
        migrations.AddField(
            model_name='make',
            name='data_id',
            field=models.IntegerField(db_index=True, help_text='auto-data.net brand ID', null=True),
        ),
        migrations.AddField(
            model_name='make',
            name='founded',
            field=models.PositiveIntegerField(blank=True, help_text='Year founded', null=True),
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='generation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='make',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(blank=True, help_text='Trim/variant name', max_length=100, null=True)),
                ('modification', models.CharField(blank=True, help_text='Engine / modification descriptor', max_length=150, null=True)),
                ('body_type', models.CharField(blank=True, max_length=100, null=True)),
                ('seats', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('doors', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('fuel_type', models.CharField(blank=True, max_length=100, null=True)),
                ('engine_displacement_cc', models.PositiveIntegerField(blank=True, null=True)),
                ('engine_cylinders', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('power_hp', models.PositiveSmallIntegerField(blank=True, help_text='hp', null=True)),
                ('power_kw', models.PositiveSmallIntegerField(blank=True, help_text='kW', null=True)),
                ('torque_nm', models.PositiveIntegerField(blank=True, help_text='Nm', null=True)),
                ('transmission', models.CharField(blank=True, max_length=50, null=True)),
                ('number_of_gears', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('drive', models.CharField(blank=True, max_length=20, null=True)),
                ('acceleration_0_100', models.DecimalField(blank=True, decimal_places=2, help_text='Seconds (0–100 km/h)', max_digits=5, null=True)),
                ('top_speed_kmh', models.PositiveIntegerField(blank=True, help_text='km/h', null=True)),
                ('fuel_consumption_l100km', models.DecimalField(blank=True, decimal_places=1, help_text='L/100km combined (WLTP)', max_digits=4, null=True)),
                ('fuel_consumption_urban_l100km', models.DecimalField(blank=True, decimal_places=1, help_text='L/100km urban', max_digits=4, null=True)),
                ('fuel_consumption_extra_urban_l100km', models.DecimalField(blank=True, decimal_places=1, help_text='L/100km extra-urban', max_digits=4, null=True)),
                ('fuel_tank_l', models.PositiveSmallIntegerField(blank=True, help_text='L', null=True)),
                ('co2_g_km', models.PositiveSmallIntegerField(blank=True, help_text='g/km', null=True)),
                ('gross_battery_capacity', models.DecimalField(blank=True, decimal_places=2, help_text='kWh', max_digits=6, null=True)),
                ('all_electric_range', models.PositiveIntegerField(blank=True, help_text='km', null=True)),
                ('average_energy_consumption', models.DecimalField(blank=True, decimal_places=2, help_text='kWh/100km (WLTP)', max_digits=6, null=True)),
                ('charging_ports', models.CharField(blank=True, choices=[('type1', 'Type 1'), ('type2', 'Type 2'), ('ccs', 'CCS'), ('chademo', 'CHAdeMO'), ('gb_t', 'GB/T')], max_length=50, null=True)),
                ('electric_motor_type', models.CharField(blank=True, max_length=100, null=True)),
                ('electric_motor_location', models.CharField(blank=True, choices=[('front', 'Front'), ('rear', 'Rear'), ('mid', 'Mid'), ('dual', 'Dual (Front + Rear)')], max_length=50, null=True)),
                ('electric_motor_code', models.CharField(blank=True, max_length=100, null=True)),
                ('electric_platform', models.CharField(blank=True, max_length=100, null=True)),
                ('length_mm', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('width_mm', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('height_mm', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('wheelbase_mm', models.PositiveIntegerField(blank=True, help_text='mm', null=True)),
                ('curb_weight_kg', models.PositiveSmallIntegerField(blank=True, help_text='kg', null=True)),
                ('max_weight_kg', models.PositiveIntegerField(blank=True, help_text='kg (GVW)', null=True)),
                ('max_load_kg', models.PositiveIntegerField(blank=True, help_text='kg', null=True)),
                ('trunk_volume_l', models.PositiveSmallIntegerField(blank=True, help_text='L', null=True)),
                ('data_id', models.IntegerField(db_index=True, help_text='auto-data.net vehicle ID', null=True)),
                ('scraped_at', models.DateTimeField(blank=True, null=True)),
                ('car_model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.carmodel')),
            ],
            options={
                'verbose_name': 'Variant',
                'verbose_name_plural': 'Variants',
                'ordering': ['car_model', 'variant'],
            },
        ),
    ]
