# Generated by Django 5.2.11 on 2026-02-24 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_trim_unique_together_remove_trim_car_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Generation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text="Generation code/name, e.g. 'E90', 'Mk IV'", max_length=50, null=True)),
                ('production_start', models.PositiveIntegerField(blank=True, help_text='Year', null=True)),
                ('production_end', models.PositiveIntegerField(blank=True, help_text='Year', null=True)),
                ('data_id', models.IntegerField(db_index=True, help_text='auto-data.net submodel ID', null=True)),
            ],
            options={
                'verbose_name': 'Generation',
                'verbose_name_plural': 'Generations',
                'ordering': ['car_model', 'production_start'],
            },
        ),
        migrations.DeleteModel(
            name='Trim',
        ),
        migrations.AlterModelOptions(
            name='variant',
            options={'ordering': ['generation', 'variant'], 'verbose_name': 'Variant', 'verbose_name_plural': 'Variants'},
        ),
        migrations.AlterUniqueTogether(
            name='carmodel',
            unique_together={('make', 'name')},
        ),
        migrations.RemoveField(
            model_name='variant',
            name='car_model',
        ),
        migrations.AlterField(
            model_name='carmodel',
            name='data_id',
            field=models.IntegerField(db_index=True, help_text='auto-data.net model ID', null=True),
        ),
        migrations.AddField(
            model_name='generation',
            name='car_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generations', to='catalog.carmodel'),
        ),
        migrations.AddField(
            model_name='variant',
            name='generation',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='catalog.generation'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='body_type',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='generation',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='production_end',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='production_start',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_from',
        ),
        migrations.RemoveField(
            model_name='carmodel',
            name='year_to',
        ),
        migrations.AlterUniqueTogether(
            name='generation',
            unique_together={('car_model', 'name')},
        ),
    ]
