# Generated by Django 5.2.11 on 2026-02-28 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_generation_delete_trim_alter_variant_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='drive',
            new_name='drivetrain',
        ),
    ]
