# Generated by Django 5.2.11 on 2026-03-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_rename_drive_variant_drivetrain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generation',
            name='name',
            field=models.CharField(blank=True, help_text="Generation code/name, e.g. 'E90', 'Mk IV'", max_length=100, null=True),
        ),
    ]
