# Generated by Django 5.2.11 on 2026-02-27 22:32

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_carmodel_make_alter_vehicle_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='country',
            field=models.CharField(blank=True, help_text='Seller country code, e.g. DE', max_length=5),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_rating',
            field=models.CharField(blank=True, help_text='e.g. GOOD_PRICE, FAIR_PRICE, HIGH_PRICE', max_length=30),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='price_rating_thresholds',
            field=models.JSONField(blank=True, default=list, help_text='Ordered list of threshold prices in EUR as floats'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='seller_type',
            field=models.CharField(blank=True, help_text='DEALER or PRIVATE', max_length=20),
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='image',
            field=models.ImageField(blank=True, help_text='Locally downloaded copy of the source image.', null=True, upload_to=vehicles.models._vehicle_image_upload_path),
        ),
    ]
