# Generated by Django 5.2.11 on 2026-02-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_rename_price_vat_applicable_to_exempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='transmission',
            field=models.CharField(blank=True, choices=[('automatic', 'Automatic'), ('manual', 'Manual')], default='automatic', max_length=16),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='transmission_type',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_vat_exempt',
            field=models.BooleanField(default=False, help_text='True for private sellers where VAT does not apply.'),
        ),
    ]
