# Generated by Django 5.2.11 on 2026-02-28 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_vehicle_transmission_vehicle_transmission_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='num_doors',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='num_gears',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
