# Generated by Django 5.2.11 on 2026-02-28 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_vehicle_num_gears_num_doors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='body_type',
            new_name='mobile_body_type',
        ),
        migrations.AddField(
            model_name='vehicle',
            name='body_type',
            field=models.CharField(blank=True, help_text='Normalized catalog slug, e.g. "suv"', max_length=100),
        ),
    ]
