# Generated by Django 5.2.11 on 2026-02-28 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_body_type_split'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='displacement_cc',
            field=models.PositiveIntegerField(blank=True, help_text='Engine displacement in cc', null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='mobile_body_type',
            field=models.CharField(blank=True, help_text='Raw body type string from mobile.de, e.g. "SUV / Geländewagen"', max_length=100),
        ),
    ]
