# Generated by Django 5.2.11 on 2026-03-01 21:40

import vehicles.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0010_vehicle_drivetrain'),
    ]

    operations = [
        migrations.CreateModel(
            name='MobileDePageCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_key', models.CharField(db_index=True, help_text='Stable cache key. Detail pages: "detail-{listing_id}". Search pages: MD5 of the normalised URL (sorted params).', max_length=64, unique=True)),
                ('listing_id', models.CharField(blank=True, db_index=True, help_text='mobile.de ad ID — only set for detail pages.', max_length=20)),
                ('page_type', models.CharField(choices=[('search', 'Search result'), ('detail', 'Ad detail')], max_length=10)),
                ('source_url', models.URLField(blank=True, max_length=2000)),
                ('html_file', models.FileField(help_text='Stored HTML dump of the scraped page.', upload_to=vehicles.models._page_cache_upload_path)),
                ('scraped_at', models.DateTimeField()),
            ],
            options={
                'verbose_name': 'mobile.de Page Cache',
                'verbose_name_plural': 'mobile.de Page Cache',
                'ordering': ['-scraped_at'],
            },
        ),
    ]
