# Generated by Django 5.2.11 on 2026-03-02 23:46

from datetime import date

from django.db import migrations, models


def populate_first_registration_date(apps, *_):
    Vehicle = apps.get_model('vehicles', 'Vehicle')
    for vehicle in Vehicle.objects.exclude(first_registration='').exclude(first_registration__isnull=True):
        raw = str(vehicle.first_registration)
        try:
            if '/' in raw:      # MM/YYYY
                month, year = raw[:7].split('/')
            elif '-' in raw:    # YYYY-MM
                year, month = raw[:7].split('-')
            else:
                continue
            vehicle.first_registration_date = date(int(year), int(month), 1)
            vehicle.save(update_fields=['first_registration_date'])
        except (ValueError, TypeError):
            pass


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_mobiledepagecache'),
    ]

    operations = [
        # Step 1: add the new DateField alongside the existing CharField
        migrations.AddField(
            model_name='vehicle',
            name='first_registration_date',
            field=models.DateField(blank=True, null=True),
        ),
        # Step 2: populate the new field from the old string values
        migrations.RunPython(populate_first_registration_date, migrations.RunPython.noop),
        # Step 3: remove the old CharField
        migrations.RemoveField(
            model_name='vehicle',
            name='first_registration',
        ),
        # Step 4: rename the new field to the canonical name
        migrations.RenameField(
            model_name='vehicle',
            old_name='first_registration_date',
            new_name='first_registration',
        ),
    ]
