# Generated by Django 5.2.11 on 2026-03-05 00:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_alter_vehicle_first_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='car_model',
            new_name='model',
        ),
    ]
