# Generated by Django 5.2.11 on 2026-03-05 01:05

from django.db import migrations, models


def translate_fuel_types(apps, _schema_editor):
    Vehicle = apps.get_model('vehicles', 'Vehicle')

    # Same logic as _translate_fuel() in scrape_mobile_de.py.
    # Hybrids are checked first so "Hybrid (Benzin)" wins over the "Benzin" rule.
    hybrid_map = [
        ('benzin', 'HYBRID_PETROL'),
        ('diesel', 'HYBRID_DIESEL'),
    ]
    fuel_map = [
        ('elektro',  'ELECTRICITY'),
        ('benzin',   'PETROL'),
        ('diesel',   'DIESEL'),
        ('erdgas',   'NATURAL_GAS'),
        ('cng',      'NATURAL_GAS'),
        ('lpg',      'LPG'),
    ]

    for vehicle in Vehicle.objects.exclude(fuel_type=''):
        lower = vehicle.fuel_type.lower()
        translated = ''
        if 'hybrid' in lower:
            for fragment, key in hybrid_map:
                if fragment in lower:
                    translated = key
                    break
        if not translated:
            for fragment, key in fuel_map:
                if fragment in lower:
                    translated = key
                    break
        if translated != vehicle.fuel_type:
            vehicle.fuel_type = translated
            vehicle.save(update_fields=['fuel_type'])


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0013_rename_vehicle_car_model_to_model'),
    ]

    operations = [
        migrations.RunPython(translate_fuel_types, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='vehicle',
            name='fuel_type',
            field=models.CharField(blank=True, choices=[('DIESEL', 'Diesel'), ('PETROL', 'Petrol'), ('ELECTRICITY', 'Electric'), ('HYBRID_PETROL', 'Hybrid (Petrol)'), ('HYBRID_DIESEL', 'Hybrid (Diesel)'), ('NATURAL_GAS', 'CNG'), ('LPG', 'LPG')], max_length=20),
        ),
    ]
